apiVersion: v1
kind: Service
metadata:
  name: lanchonete-lb-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  selector:
    app: lanchonete-deployment
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
