name: ci

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build
        run: ./gradlew build --no-daemon

#      - name: Test
#
#        run: ./gradlew build --no-daemon
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#          cache: 'gradle'



