name: 📦🚀 [Production] Lanchonete API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-production:
    uses: ./.github/workflows/cd.yaml
    with:
      aws_region: "us-east-1"
      app_env: prod
      ecr_repository: lanchonete-prd-repository
      ecs_cluster: cluster
      ecs_service: service
      ecs_task_definition: .aws/task-definition.json
      container_name: lanchonete
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
